#!/usr/sbin/nft -f

add table inet hi_filter
delete table inet hi_filter

table inet hi_filter {
  chain input {
    type filter hook input priority filter; policy drop;

    ct state established,related accept
    ct state invalid drop
    iif "lo" accept
    meta l4proto { icmp, ipv6-icmp } accept
    tcp dport 22 ct state new accept
  }
}
