#!/usr/bin/env node
/**
 * Builds a Material Symbols (Outlined) font that holds only the icons the app uses.
 *
 * Icon names are ligatures, so the subset keeps the `liga` rules for those names and the letters
 * that spell them, but drops every other icon. HarfBuzz layout closure is disabled: with it on,
 * keeping "a"–"z" would pull every ligature (the whole font) back in. Axes are pinned to the
 * values in styles.scss (FILL 0, wght 400, GRAD 0, opsz 24).
 *
 * Output (git-ignored): src/generated/material-symbols/{material-symbols-outlined.woff2,outlined.css}.
 * The run is skipped when the icon list and inputs are unchanged.
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as hb from 'harfbuzzjs';

const require = createRequire(import.meta.url);
const subsetFont = require('subset-font');
const fontverter = require('fontverter');

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = join(root, 'src', 'app');
const outDir = join(root, 'src', 'generated', 'material-symbols');
const sourceFont = require.resolve('material-symbols/material-symbols-outlined.woff2');
const PINNED_AXES = { FILL: 0, wght: 400, GRAD: 0, opsz: 24 };
const MAX_BYTES = 200 * 1024;

/** Names that appear only in data the scanner cannot see. Add to this list when an icon renders as text. */
const EXTRA_ICONS = [];

const NAME = /^[a-z][a-z0-9_]{1,40}$/;
const PATTERNS = [
  /<mat-icon[^>]*>\s*([a-z][a-z0-9_]*)\s*<\/mat-icon>/g,
  /\bicon\s*=\s*"([a-z][a-z0-9_]*)"/gi,
  /fontIcon\s*=\s*"([a-z][a-z0-9_]*)"/g,
  /'([a-z][a-z0-9_]*)'/g,
];

async function sourceFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        return sourceFiles(path);
      }
      return /\.(ts|html)$/.test(entry.name) && !entry.name.endsWith('.spec.ts') ? [path] : [];
    }),
  );
  return files.flat();
}

async function candidateNames() {
  const names = new Set(EXTRA_ICONS);
  for (const file of await sourceFiles(sourceDir)) {
    const text = await readFile(file, 'utf8');
    for (const pattern of PATTERNS) {
      for (const match of text.matchAll(pattern)) {
        if (NAME.test(match[1])) {
          names.add(match[1]);
        }
      }
    }
  }
  return [...names].sort();
}

function shaper(fontData) {
  const face = new hb.Face(new hb.Blob(fontData));
  const font = new hb.Font(face);
  return {
    face,
    font,
    glyphsFor(text) {
      const buffer = new hb.Buffer();
      buffer.addText(text);
      buffer.guessSegmentProperties();
      hb.shape(font, buffer);
      return buffer.getGlyphInfos().map((info) => info.codepoint);
    },
  };
}

function ligatureCodepoints(names, original) {
  const glyphToCodepoint = new Map();
  for (const unicode of original.face.collectUnicodes()) {
    if (unicode >= 0xe000) {
      const glyph = original.font.nominalGlyph(unicode);
      if (glyph !== undefined && !glyphToCodepoint.has(glyph)) {
        glyphToCodepoint.set(glyph, unicode);
      }
    }
  }
  const icons = new Map();
  for (const name of names) {
    const glyphs = original.glyphsFor(name);
    if (glyphs.length === 1 && glyphToCodepoint.has(glyphs[0])) {
      icons.set(name, { glyph: glyphs[0], codepoint: glyphToCodepoint.get(glyphs[0]) });
    }
  }
  return icons;
}

function stylesheet() {
  return `/* Generated by scripts/subset-icons.mjs. Do not edit. */
@font-face {
  font-family: 'Material Symbols Outlined';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url('./material-symbols-outlined.woff2') format('woff2');
}

.material-symbols-outlined {
  font-family: 'Material Symbols Outlined';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
  font-feature-settings: 'liga';
}
`;
}

async function main() {
  const names = await candidateNames();
  const woff2 = await readFile(sourceFont);
  const scriptSource = await readFile(fileURLToPath(import.meta.url));
  const fingerprint = createHash('sha256')
    .update(JSON.stringify(names))
    .update(woff2)
    .update(scriptSource)
    .digest('hex');
  const manifestPath = join(outDir, 'manifest.json');
  const previous = await readFile(manifestPath, 'utf8').then(JSON.parse, () => null);
  if (previous?.fingerprint === fingerprint) {
    console.log(`subset-icons: up to date (${previous.icons.length} icons, ${previous.bytes} bytes)`);
    return;
  }

  const truetype = await fontverter.convert(woff2, 'truetype');
  const original = shaper(truetype);
  const icons = ligatureCodepoints(names, original);
  const missing = EXTRA_ICONS.filter((name) => !icons.has(name));
  if (missing.length) {
    throw new Error(`Unknown Material Symbols in EXTRA_ICONS: ${missing.join(', ')}`);
  }

  const letters = [...new Set([...icons.keys()].join(''))].join('');
  const pua = [...icons.values()].map(({ codepoint }) => String.fromCodePoint(codepoint)).join('');
  const subset = await subsetFont(truetype, letters + pua, {
    targetFormat: 'woff2',
    noLayoutClosure: true,
    variationAxes: PINNED_AXES,
  });

  const check = shaper(await fontverter.convert(subset, 'truetype'));
  const broken = [...icons.keys()].filter((name) => check.glyphsFor(name).length !== 1);
  if (broken.length) {
    throw new Error(`Ligatures lost in the subset: ${broken.join(', ')}`);
  }
  if (subset.byteLength > MAX_BYTES) {
    throw new Error(`Subset is ${subset.byteLength} bytes; the limit is ${MAX_BYTES}.`);
  }

  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, 'material-symbols-outlined.woff2'), subset);
  await writeFile(join(outDir, 'outlined.css'), stylesheet());
  const manifest = { fingerprint, bytes: subset.byteLength, icons: [...icons.keys()] };
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(
    `subset-icons: wrote ${relative(root, outDir)} (${icons.size} icons, ${subset.byteLength} bytes, from ${woff2.byteLength})`,
  );
}

main().catch((error) => {
  console.error(`subset-icons: ${error.message}`);
  process.exit(1);
});
