// <auto-generated />
using System;
using HockeyIndex.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HockeyIndex.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("00000000000004_Venues")]
    partial class Venues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HockeyIndex.Api.Domain.BlocklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_blocklist");

                    b.HasIndex("Kind", "Value")
                        .IsUnique()
                        .HasDatabaseName("ux_blocklist_kind_value");

                    b.ToTable("blocklist", null, t =>
                        {
                            t.HasCheckConstraint("ck_blocklist_kind", "kind IN ('phone','domain')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Breaker", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("OpenUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_until");

                    b.Property<string>("OpenedBy")
                        .HasColumnType("text")
                        .HasColumnName("opened_by");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Name")
                        .HasName("pk_breakers");

                    b.ToTable("breakers", null, t =>
                        {
                            t.HasCheckConstraint("ck_breakers_opened_by", "opened_by IN ('auto','twilio_webhook','admin')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsVoip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_voip");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneLineType")
                        .HasColumnType("text")
                        .HasColumnName("phone_line_type");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<DateTimeOffset>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_verified_at");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_hosts");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_hosts_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_hosts_normalized_user_name");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_hosts_phone_number");

                    b.HasIndex(new[] { "NormalizedEmail" }, "ux_hosts_verified_email")
                        .IsUnique()
                        .HasDatabaseName("ux_hosts_verified_email")
                        .HasFilter("email_confirmed");

                    b.ToTable("hosts", null, t =>
                        {
                            t.HasCheckConstraint("ck_hosts_status", "status IN ('active','banned')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.LoginToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("code_expires_at");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<byte[]>("LinkHash")
                        .HasColumnType("bytea")
                        .HasColumnName("link_hash");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.HasKey("Id")
                        .HasName("pk_login_tokens");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_login_tokens_created_at");

                    b.HasIndex("LinkHash")
                        .IsUnique()
                        .HasDatabaseName("ux_login_tokens_link_hash")
                        .HasFilter("link_hash IS NOT NULL");

                    b.HasIndex("HostId", "Purpose", "CreatedAt")
                        .HasDatabaseName("ix_login_tokens_host_purpose");

                    b.ToTable("login_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_login_tokens_attempts", "attempts BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_login_tokens_purpose", "purpose IN ('email_confirm','email_login','recycle_check')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.OtpLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("IpKeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ip_key_hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LineType")
                        .HasColumnType("text")
                        .HasColumnName("line_type");

                    b.Property<string>("NpaNxx")
                        .HasColumnType("char(6)")
                        .HasColumnName("npa_nxx");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<byte[]>("TargetHash")
                        .HasColumnType("bytea")
                        .HasColumnName("target_hash");

                    b.HasKey("Id")
                        .HasName("pk_otp_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_otp_log_created_at");

                    b.HasIndex("IpKeyHash", "CreatedAt")
                        .HasDatabaseName("ix_otp_log_ip_created");

                    b.HasIndex("NpaNxx", "CreatedAt")
                        .HasDatabaseName("ix_otp_log_npa_nxx_created");

                    b.HasIndex("TargetHash", "CreatedAt")
                        .HasDatabaseName("ix_otp_log_target_created");

                    b.ToTable("otp_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_otp_log_channel", "channel IN ('sms','email')");

                            t.HasCheckConstraint("ck_otp_log_kind", "kind IN ('send','verify')");

                            t.HasCheckConstraint("ck_otp_log_outcome", "outcome IN ('sent','verified','failed','limited','rejected_region','rejected_blocklist','rejected_banned','rejected_line_type','turnstile_failed','breaker_open','budget_exhausted','invite_required')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.ProviderUsage", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Calls")
                        .HasColumnType("integer")
                        .HasColumnName("calls");

                    b.Property<int>("Cap")
                        .HasColumnType("integer")
                        .HasColumnName("cap");

                    b.HasKey("Provider", "HostId", "Day")
                        .HasName("pk_provider_usage");

                    b.ToTable("provider_usage", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.SignupInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_signup_invites");

                    b.HasIndex("PhoneE164")
                        .HasDatabaseName("ix_signup_invites_phone_e164");

                    b.ToTable("signup_invites", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.UrlVerdict", b =>
                {
                    b.Property<byte[]>("UrlHash")
                        .HasColumnType("bytea")
                        .HasColumnName("url_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.PrimitiveCollection<string[]>("ThreatTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("threat_types");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verdict");

                    b.HasKey("UrlHash")
                        .HasName("pk_url_verdicts");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_url_verdicts_expires_at");

                    b.ToTable("url_verdicts", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Point>("Geo")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("geo");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_normalized");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_place_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("public_id")
                        .IsFixedLength();

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("region")
                        .IsFixedLength();

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_venues_created_by");

                    b.HasIndex("Geo")
                        .HasDatabaseName("ix_venues_geo");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geo"), "gist");

                    b.HasIndex("MergedIntoId")
                        .HasDatabaseName("ix_venues_merged_into_id");

                    b.HasIndex("NameNormalized")
                        .HasDatabaseName("ix_venues_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameNormalized"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameNormalized"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_venues_public_id");

                    b.HasIndex("Provider", "ProviderPlaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_venues_provider_place")
                        .HasFilter("provider_place_id IS NOT NULL");

                    b.ToTable("venues", null, t =>
                        {
                            t.HasCheckConstraint("ck_venues_country", "country IN ('US','CA')");

                            t.HasCheckConstraint("ck_venues_provider", "provider IN ('mapbox','geocodio','esri','osm','manual')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_host_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_host_claims_user_id");

                    b.ToTable("host_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_host_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_host_logins_user_id");

                    b.ToTable("host_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_host_tokens");

                    b.ToTable("host_tokens", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.LoginToken", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_tokens_hosts_host_id");
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Venue", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_venues_hosts_created_by");

                    b.HasOne("HockeyIndex.Api.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_venues_venues_merged_into_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_host_claims_hosts_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_host_logins_hosts_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_host_tokens_hosts_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
