// <auto-generated />
using System;
using HockeyIndex.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace HockeyIndex.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HockeyIndex.Api.Domain.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_log_created_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_log_target");

                    b.ToTable("audit_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_reason", "length(btrim(reason)) > 0");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.BlocklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_blocklist");

                    b.HasIndex("Kind", "Value")
                        .IsUnique()
                        .HasDatabaseName("ux_blocklist_kind_value");

                    b.ToTable("blocklist", null, t =>
                        {
                            t.HasCheckConstraint("ck_blocklist_kind", "kind IN ('phone','domain')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Breaker", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("OpenUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_until");

                    b.Property<string>("OpenedBy")
                        .HasColumnType("text")
                        .HasColumnName("opened_by");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Name")
                        .HasName("pk_breakers");

                    b.ToTable("breakers", null, t =>
                        {
                            t.HasCheckConstraint("ck_breakers_opened_by", "opened_by IN ('auto','twilio_webhook','admin')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.EventStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_event_status_changes");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_status_changes_event_id");

                    b.HasIndex("HostId", "ToStatus", "At")
                        .HasDatabaseName("ix_event_status_changes_host_to_at");

                    b.ToTable("event_status_changes", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_status_changes_from_status", "from_status IN ('draft','published','cancelled','hidden','archived')");

                            t.HasCheckConstraint("ck_event_status_changes_to_status", "to_status IN ('draft','published','cancelled','hidden','archived')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.HockeyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTime>("EndsLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ends_local");

                    b.Property<int?>("FeeCents")
                        .HasColumnType("integer")
                        .HasColumnName("fee_cents");

                    b.Property<string>("HiddenFromStatus")
                        .HasColumnType("text")
                        .HasColumnName("hidden_from_status");

                    b.Property<string>("HiddenReason")
                        .HasColumnType("text")
                        .HasColumnName("hidden_reason");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("JoinInstructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("join_instructions");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("Notice")
                        .HasColumnType("text")
                        .HasColumnName("notice");

                    b.Property<string>("PendingJoinInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("pending_join_instructions");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("public_id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("PublishRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_requested_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RinkLabel")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rink_label");

                    b.Property<string>("ScheduleText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("schedule_text");

                    b.Property<NpgsqlRange<int>>("SkillRange")
                        .HasColumnType("int4range")
                        .HasColumnName("skill_range");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTime>("StartsLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starts_local");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_events_public_id");

                    b.HasIndex("PublishRequestedAt")
                        .HasDatabaseName("ix_events_publish_requested")
                        .HasFilter("publish_requested_at IS NOT NULL");

                    b.HasIndex("SkillRange")
                        .HasDatabaseName("ix_events_skill")
                        .HasFilter("status IN ('published','cancelled')");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SkillRange"), "gist");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_events_venue_id");

                    b.HasIndex("Status", "EndsAt")
                        .HasDatabaseName("ix_events_status_ends");

                    b.HasIndex("HostId", "Status", "EndsAt")
                        .HasDatabaseName("ix_events_host_status");

                    b.HasIndex(new[] { "Id" }, "ix_events_pending_ji")
                        .HasDatabaseName("ix_events_pending_ji")
                        .HasFilter("pending_join_instructions IS NOT NULL");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_archived_at", "status <> 'archived' OR archived_at IS NOT NULL");

                            t.HasCheckConstraint("ck_events_currency", "currency IN ('CAD','USD')");

                            t.HasCheckConstraint("ck_events_fee_cents", "fee_cents IS NULL OR fee_cents BETWEEN 0 AND 100000");

                            t.HasCheckConstraint("ck_events_hidden_from_status", "hidden_from_status IS NULL OR hidden_from_status IN ('published','cancelled','archived')");

                            t.HasCheckConstraint("ck_events_hidden_from_status_required", "status <> 'hidden' OR hidden_from_status IS NOT NULL");

                            t.HasCheckConstraint("ck_events_hidden_reason", "hidden_reason IS NULL OR hidden_reason IN ('admin','reports','link_scan','domain_blocklist','host_banned')");

                            t.HasCheckConstraint("ck_events_hidden_reason_required", "status <> 'hidden' OR hidden_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_events_hidden_reason_scope", "status IN ('hidden','archived') OR hidden_reason IS NULL");

                            t.HasCheckConstraint("ck_events_local_time_order", "ends_local > starts_local");

                            t.HasCheckConstraint("ck_events_notice", "notice IS NULL OR notice IN ('publish_blocked','publish_limit_reached','publish_scan_expired','join_instructions_blocked')");

                            t.HasCheckConstraint("ck_events_pending_join_not_draft", "pending_join_instructions IS NULL OR status <> 'draft'");

                            t.HasCheckConstraint("ck_events_public_id", "public_id ~ '^[a-z2-7]{10}$'");

                            t.HasCheckConstraint("ck_events_publish_requested", "publish_requested_at IS NULL OR status = 'draft'");

                            t.HasCheckConstraint("ck_events_schedule_text", "type <> 'scrimmage' OR schedule_text IS NULL");

                            t.HasCheckConstraint("ck_events_skill_range", "skill_range <@ int4range(0,7,'[]') AND NOT isempty(skill_range) AND NOT lower_inf(skill_range) AND NOT upper_inf(skill_range)");

                            t.HasCheckConstraint("ck_events_status", "status IN ('draft','published','cancelled','hidden','archived')");

                            t.HasCheckConstraint("ck_events_time_order", "ends_at > starts_at");

                            t.HasCheckConstraint("ck_events_type", "type IN ('scrimmage','league','tournament')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsVoip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_voip");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneLineType")
                        .HasColumnType("text")
                        .HasColumnName("phone_line_type");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<DateTimeOffset>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_verified_at");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_hosts");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_hosts_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_hosts_normalized_user_name");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_hosts_phone_number");

                    b.HasIndex(new[] { "NormalizedEmail" }, "ux_hosts_verified_email")
                        .IsUnique()
                        .HasDatabaseName("ux_hosts_verified_email")
                        .HasFilter("email_confirmed");

                    b.ToTable("hosts", null, t =>
                        {
                            t.HasCheckConstraint("ck_hosts_status", "status IN ('active','banned')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.JobRun", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_name");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_started_at");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_succeeded_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<long?>("RowsAffected")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_affected");

                    b.HasKey("JobName")
                        .HasName("pk_job_runs");

                    b.ToTable("job_runs", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.LinkScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FinalHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("final_host");

                    b.Property<string>("FinalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("final_url");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<int>("RedirectHops")
                        .HasColumnType("integer")
                        .HasColumnName("redirect_hops");

                    b.PrimitiveCollection<string[]>("ThreatTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("threat_types");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_link_scans");

                    b.HasIndex("FinalHost")
                        .HasDatabaseName("ix_link_scans_final_host");

                    b.HasIndex("EventId", "CheckedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_link_scans_event_checked");

                    b.ToTable("link_scans", null, t =>
                        {
                            t.HasCheckConstraint("ck_link_scans_provider", "provider IN ('webrisk','blocklist','none')");

                            t.HasCheckConstraint("ck_link_scans_verdict", "verdict IN ('safe','malicious','unknown')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.LoginToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("code_expires_at");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<byte[]>("LinkHash")
                        .HasColumnType("bytea")
                        .HasColumnName("link_hash");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.HasKey("Id")
                        .HasName("pk_login_tokens");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_login_tokens_created_at");

                    b.HasIndex("LinkHash")
                        .IsUnique()
                        .HasDatabaseName("ux_login_tokens_link_hash")
                        .HasFilter("link_hash IS NOT NULL");

                    b.HasIndex("HostId", "Purpose", "CreatedAt")
                        .HasDatabaseName("ix_login_tokens_host_purpose");

                    b.ToTable("login_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_login_tokens_attempts", "attempts BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_login_tokens_purpose", "purpose IN ('email_confirm','email_login','recycle_check')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.OtpLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("IpKeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ip_key_hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LineType")
                        .HasColumnType("text")
                        .HasColumnName("line_type");

                    b.Property<string>("NpaNxx")
                        .HasColumnType("char(6)")
                        .HasColumnName("npa_nxx");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<byte[]>("TargetHash")
                        .HasColumnType("bytea")
                        .HasColumnName("target_hash");

                    b.HasKey("Id")
                        .HasName("pk_otp_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_otp_log_created_at");

                    b.HasIndex("IpKeyHash", "CreatedAt")
                        .HasDatabaseName("ix_otp_log_ip_created");

                    b.HasIndex("NpaNxx", "CreatedAt")
                        .HasDatabaseName("ix_otp_log_npa_nxx_created");

                    b.HasIndex("TargetHash", "CreatedAt")
                        .HasDatabaseName("ix_otp_log_target_created");

                    b.ToTable("otp_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_otp_log_channel", "channel IN ('sms','email')");

                            t.HasCheckConstraint("ck_otp_log_kind", "kind IN ('send','verify')");

                            t.HasCheckConstraint("ck_otp_log_outcome", "outcome IN ('sent','verified','failed','limited','rejected_region','rejected_blocklist','rejected_banned','rejected_line_type','turnstile_failed','breaker_open','budget_exhausted','invite_required')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.ProviderUsage", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Calls")
                        .HasColumnType("integer")
                        .HasColumnName("calls");

                    b.Property<int>("Cap")
                        .HasColumnType("integer")
                        .HasColumnName("cap");

                    b.HasKey("Provider", "HostId", "Day")
                        .HasName("pk_provider_usage");

                    b.ToTable("provider_usage", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("details");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reason");

                    b.Property<byte[]>("ReporterHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("reporter_hash");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("EventId", "ReporterHash")
                        .IsUnique()
                        .HasDatabaseName("ux_reports_event_reporter");

                    b.HasIndex("ReporterHash", "CreatedAt")
                        .HasDatabaseName("ix_reports_reporter_created");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_reports_reason", "reason IN ('scam','spam','offensive','inaccurate','other')");
                        });
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.SignupInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_signup_invites");

                    b.HasIndex("PhoneE164")
                        .HasDatabaseName("ix_signup_invites_phone_e164");

                    b.ToTable("signup_invites", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.UrlVerdict", b =>
                {
                    b.Property<byte[]>("UrlHash")
                        .HasColumnType("bytea")
                        .HasColumnName("url_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.PrimitiveCollection<string[]>("ThreatTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("threat_types");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verdict");

                    b.HasKey("UrlHash")
                        .HasName("pk_url_verdicts");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_url_verdicts_expires_at");

                    b.ToTable("url_verdicts", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Point>("Geo")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("geo");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_normalized");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_place_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("public_id")
                        .IsFixedLength();

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("region")
                        .IsFixedLength();

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_venues_created_by");

                    b.HasIndex("Geo")
                        .HasDatabaseName("ix_venues_geo");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geo"), "gist");

                    b.HasIndex("MergedIntoId")
                        .HasDatabaseName("ix_venues_merged_into_id");

                    b.HasIndex("NameNormalized")
                        .HasDatabaseName("ix_venues_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameNormalized"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameNormalized"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_venues_public_id");

                    b.HasIndex("Provider", "ProviderPlaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_venues_provider_place")
                        .HasFilter("provider_place_id IS NOT NULL");

                    b.ToTable("venues", null, t =>
                        {
                            t.HasCheckConstraint("ck_venues_country", "country IN ('US','CA')");

                            t.HasCheckConstraint("ck_venues_provider", "provider IN ('mapbox','geocodio','esri','osm','manual')");

                            t.HasCheckConstraint("ck_venues_public_id", "public_id ~ '^[a-z2-7]{10}$'");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_host_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_host_claims_user_id");

                    b.ToTable("host_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_host_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_host_logins_user_id");

                    b.ToTable("host_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_host_tokens");

                    b.ToTable("host_tokens", (string)null);
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.EventStatusChange", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.HockeyEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_status_changes_events_event_id");
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.HockeyEvent", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_asp_net_users_host_id");

                    b.HasOne("HockeyIndex.Api.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_venues_venue_id");
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.LinkScan", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.HockeyEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_scans_events_event_id");
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.LoginToken", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_tokens_hosts_host_id");
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Report", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.HockeyEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_events_event_id");
                });

            modelBuilder.Entity("HockeyIndex.Api.Domain.Venue", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_venues_hosts_created_by");

                    b.HasOne("HockeyIndex.Api.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_venues_venues_merged_into_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_host_claims_hosts_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_host_logins_hosts_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HockeyIndex.Api.Domain.Host", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_host_tokens_hosts_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
